services:
  win10:
    image: docker.io/vaggeliskls/windows-in-docker-container:latest
    platform: linux/amd64
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file: .env
    stdin_open: true
    tty: true
    privileged: true
    cgroup: host
    restart: always
    volumes:
      - ./Vagrantfile:/app/Vagrantfile
    # runtime: nvidia
    ports:
      - 3389:3389
      - 2222:2222