name: LiMint 0.0.11

on:
  workflow_dispatch:
    inputs:
      memory-size:
        description: 'Memory size in MB'
        default: '8192'

jobs:
  desktop-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download Linux Mint ISO
        run: |
          wget -O linuxmint.iso https://mirrors.cicku.me/linuxmint/iso/stable/22.2/linuxmint-22.2-xfce-64bit.iso
      
      - name: Verify ISO Integrity
        run: |
          sha256sum linuxmint.iso
          echo "ISO downloaded successfully"
      
      - name: Create Disk Image
        run: |
          sudo apt-get install -y qemu-utils
          qemu-img create disk.qcow2 50G
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            gcc \
            libssl-dev \
            pkg-config \
            libglib2.0-dev \
            libgtk-3-dev \
            libpulse-dev \
            libibus-1.0-dev \
            ninja-build \
            meson \
            libavahi-compat-libdnssd-dev \
            libsystemd-dev \
            libpipewire-0.3-dev \
            libspa-0.2-dev \
            libfdk-aac-dev \
            libopus-dev \
            libvpx-dev
      
      - name: Install Selkies Server
        run: |
          git clone https://github.com/selkies-project/selkies-server.git
          cd selkies-server
          meson setup builddir
          ninja -C builddir
          sudo ninja -C builddir install
      
      - name: Configure Selkies Server
        run: |
          sudo mkdir -p /etc/selkies/server
          
          sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
            -keyout /etc/selkies/server/key.pem \
            -out /etc/selkies/server/cert.pem \
            -subj "/CN=localhost" \
            -extensions EXT -config <(cat /usr/lib/ssl/openssl.cnf <(printf "[EXT]\nextendedKeyUsage=digitalSignature"))
          
          cat <<EOF | sudo tee /etc/selkies/server/config.toml
          [server]
          address = "0.0.0.0"
          port = 443
          
          [tls]
          cert_path = "/etc/selkies/server/cert.pem"
          key_path = "/etc/selkies/server/key.pem"
          
          [auth]
          token = "$(openssl rand -base64 32)"
          
          [logging]
          level = "info"
          format = "json"
          
          [session]
          timeout = 3600
          EOF
      
      - name: Start Selkies Server
        run: |
          sudo systemctl daemon-reload
          sudo systemctl enable selkies-server.service
          sudo systemctl start selkies-server
          sleep 10
      
      - name: Start Linux Mint VM
        id: vm
        uses: etchdroid/qemu-kvm-action/start@v1
        with:
          kernel: ''
          initrd: ''
          append: 'console=ttyS0 earlyprintk=uart,115200'
          flags: |
            -enable-kvm
            -m ${{ github.event.inputs.memory-size }}
            -smp 4
            -device virtio-blk-device,drive=hd0
            -drive if=none,id=hd0,file=disk.qcow2,format=qcow2
            -device virtio-net-device,netdev=eth0
            -netdev user,id=eth0,hostfwd=tcp::2222-:22,tcp::443-:443
            -device virtio-gpu-pci
            -vga virtio
            -cdrom linuxmint.iso
            -monitor stdio
          run: |
            sleep 3600
            
      - name: Configure VM Selkies Client
        run: |
          echo "[selkies]
          server = ws://localhost:443
          display = :0
          fullscreen = True
          resolution = 1920x1080" | sudo tee /etc/selkies/client.conf
          
          sudo systemctl start selkies-client.service
          sleep 3600
