name: Build Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile  # Adjust the path if your Dockerfile is in a different location
          push: false  # Set to true if you want to push the image to a registry
          tags: qemu:latest  # Change 'my-image' to your desired image name

      - name: list images
        run: |
          docker images
