name: 0.0.1

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Run container
        run: |
          docker run -d \
          --name=webtop \
          -e PUID=1000 \
          -e PGID=1000 \
          -e TZ=Etc/UTC \
          -e CHROME_CLI=https://www.linuxserver.io/ `#optional` \
          -p 3000:3000 \
          -p 3001:3001 \
          -v /config:/config \
          --shm-size="1gb" \
          --restart unless-stopped \
          lscr.io/linuxserver/webtop:debian-icewm

      - name: Show running containers
        run: docker ps
        
      - name: Run f1r3Flared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          mv cloudflared-linux-amd64 cloudflared
          ./cloudflared --version
          ./cloudflared tunnel --url http://localhost:3000

      - name: Keep alive for 5 hours
        run: sleep 18000
        
